'use client';

import { useState, useMemo, useEffect, useCallback } from 'react';
import NumberInput from '@/components/calculator/NumberInput';
import ResultCard from '@/components/calculator/ResultCard';
import CalculatorForm from '@/components/calculator/CalculatorForm';
import Breadcrumb from '@/components/ui/Breadcrumb';
import ShareButton from '@/components/ui/ShareButton';
import { WebApplicationJsonLd, FAQJsonLd, BreadcrumbJsonLd } from '@/components/seo/JsonLd';
import AdSense from '@/components/ads/AdSense';
import { calculateROI } from '@/lib/calculators/roi';
import { formatCurrency, formatPercent } from '@/lib/format';
import { SITE_URL } from '@/lib/constants';
import { buildShareUrl, getParamNumber } from '@/lib/share';
import { trackCalculatorUse } from '@/lib/analytics';
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  BarChart,
  Bar,
  ReferenceLine,
} from 'recharts';

const FAQ_ITEMS = [
  {
    question: 'What is ROI (Return on Investment)?',
    answer:
      'ROI measures the gain or loss generated by an investment relative to its initial cost. It is expressed as a percentage: ROI = (Net Profit / Initial Investment) × 100. A positive ROI means you profited; a negative ROI means you lost money. ROI is one of the most widely used metrics to evaluate investment performance.',
  },
  {
    question: 'What is the difference between total return and annualized return (CAGR)?',
    answer:
      'Total return shows the overall percentage gain or loss over the entire holding period, regardless of how long you held the investment. Annualized return (CAGR — Compound Annual Growth Rate) converts that total return into an equivalent yearly rate. CAGR is more useful for comparing investments held over different time horizons because it accounts for time.',
  },
  {
    question: 'How is CAGR calculated?',
    answer:
      'CAGR = ((Final Value / Initial Investment) ^ (1 / Years)) − 1. For example, if a $10,000 investment grew to $15,000 over 5 years, CAGR = (1.5)^(1/5) − 1 ≈ 8.45% per year. This means the investment grew at a steady 8.45% annually to reach the same result.',
  },
  {
    question: 'Should I include transaction costs and fees?',
    answer:
      'Yes. Fees, commissions, taxes, and other costs directly reduce your net profit. Including them gives you a more accurate picture of actual investment performance. Even small annual fees compound over time and can significantly reduce long-term returns — always factor them in when comparing investment options.',
  },
  {
    question: 'What is a good ROI?',
    answer:
      'A "good" ROI depends on the investment type and time period. The S&P 500 has historically averaged around 10% annually before inflation. Real estate, private equity, and startups often target higher returns to compensate for additional risk. Always compare ROI relative to a relevant benchmark and adjust for risk and time horizon.',
  },
];

const tooltipStyle = {
  backgroundColor: 'rgb(15 23 42)',
  border: '1px solid rgb(51 65 85)',
  borderRadius: '10px',
  padding: '10px 14px',
  color: 'rgb(241 245 249)',
  boxShadow: '0 10px 25px rgba(0, 0, 0, 0.4)',
};

export default function ROICalculator() {
  const [initialInvestment, setInitialInvestment] = useState(10000);
  const [finalValue, setFinalValue] = useState(15000);
  const [years, setYears] = useState(5);
  const [additionalCosts, setAdditionalCosts] = useState(0);
  const [tracked, setTracked] = useState(false);

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const ii = getParamNumber(params, 'ii');
    const fv = getParamNumber(params, 'fv');
    const y = getParamNumber(params, 'y');
    const c = getParamNumber(params, 'c');
    if (ii !== null) setInitialInvestment(ii);
    if (fv !== null) setFinalValue(fv);
    if (y !== null) setYears(y);
    if (c !== null) setAdditionalCosts(c);
  }, []);

  const getShareUrl = useCallback(
    () =>
      buildShareUrl('/calculator/roi', {
        ii: initialInvestment,
        fv: finalValue,
        y: years,
        c: additionalCosts,
      }),
    [initialInvestment, finalValue, years, additionalCosts],
  );

  const result = useMemo(
    () =>
      calculateROI({
        initialInvestment,
        finalValue,
        years,
        additionalCosts,
      }),
    [initialInvestment, finalValue, years, additionalCosts],
  );

  useEffect(() => {
    if (tracked) return;
    if (Number.isFinite(result.netProfit) && initialInvestment > 0) {
      trackCalculatorUse('roi');
      setTracked(true);
    }
  }, [result.netProfit, initialInvestment, tracked]);

  const isProfit = result.netProfit >= 0;

  const chartData = useMemo(
    () =>
      result.yearlyBreakdown.map((row) => ({
        year: `Year ${row.year}`,
        Value: Math.round(row.value),
        'Cumulative Return': parseFloat(row.cumulativeReturn.toFixed(2)),
      })),
    [result],
  );

  const barData = useMemo(
    () => [
      {
        name: 'Investment',
        Initial: Math.round(initialInvestment),
        'Net Profit': isProfit ? Math.round(result.netProfit) : 0,
        Loss: !isProfit ? Math.round(result.netProfit) : 0,
      },
    ],
    [initialInvestment, result.netProfit, isProfit],
  );

  const pageUrl = `${SITE_URL}/calculator/roi`;

  return (
    <>
      <WebApplicationJsonLd
        name="ROI Calculator"
        description="Calculate total return, net profit, and annualized return (CAGR) for any investment. Visualize growth year by year."
        url={pageUrl}
      />
      <FAQJsonLd questions={FAQ_ITEMS} />
      <BreadcrumbJsonLd
        items={[
          { name: 'Home', url: SITE_URL },
          { name: 'Calculators', url: `${SITE_URL}/calculator` },
          { name: 'ROI Calculator', url: pageUrl },
        ]}
      />

      <div className="max-w-6xl mx-auto px-4 py-8">
        {/* Breadcrumb */}
        <Breadcrumb
          items={[
            { label: 'Home', href: '/' },
            { label: 'Calculators', href: '/calculator' },
            { label: 'ROI Calculator' },
          ]}
        />

        {/* Page Header */}
        <div className="mt-6 mb-8">
          <div className="flex items-start justify-between gap-4 mb-2">
            <h1 className="text-3xl sm:text-4xl font-bold text-text-primary">
              ROI Calculator
            </h1>
            <ShareButton getShareUrl={getShareUrl} slug="roi" />
          </div>
          <p className="text-text-secondary text-lg">
            Calculate total return, net profit, and annualized CAGR for any investment.
          </p>
        </div>

        {/* Top Ad */}
        <AdSense slot="header" variant="banner" />

        {/* Two Column Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mt-6">
          {/* Left Column - Calculator Form */}
          <div className="lg:col-span-2">
            <CalculatorForm>
              <NumberInput
                label="Initial Investment"
                value={initialInvestment}
                onChange={setInitialInvestment}
                min={1}
                max={10000000}
                step={1000}
                prefix="$"
                showSlider
              />

              <NumberInput
                label="Final Value"
                value={finalValue}
                onChange={setFinalValue}
                min={0}
                max={10000000}
                step={1000}
                prefix="$"
                showSlider
              />

              <NumberInput
                label="Holding Period"
                value={years}
                onChange={setYears}
                min={1}
                max={50}
                step={1}
                suffix="years"
                showSlider
              />

              <NumberInput
                label="Additional Costs (fees, taxes, etc.)"
                value={additionalCosts}
                onChange={setAdditionalCosts}
                min={0}
                max={1000000}
                step={100}
                prefix="$"
                showSlider
              />
            </CalculatorForm>
          </div>

          {/* Right Column - Results & Ad */}
          <div className="space-y-6">
            <ResultCard
              title="Investment Summary"
              items={[
                {
                  label: 'Net Profit / Loss',
                  value: formatCurrency(result.netProfit),
                  highlight: true,
                },
                {
                  label: 'Total Return',
                  value: formatPercent(result.totalReturnPct),
                },
                {
                  label: 'Annualized Return (CAGR)',
                  value: formatPercent(result.annualizedReturnPct),
                  subtext: `over ${years} year${years !== 1 ? 's' : ''}`,
                },
                {
                  label: 'Final Value',
                  value: formatCurrency(finalValue - Math.max(0, additionalCosts)),
                },
              ]}
            />

            <AdSense slot="sidebar" variant="sidebar" />
          </div>
        </div>

        {/* Charts Section */}
        {result.yearlyBreakdown.length > 0 && (
          <div className="mt-8 space-y-8">
            {/* Area Chart - Investment Growth */}
            <div className="bg-dark-surface border border-dark-border rounded-xl p-6">
              <h3 className="text-lg font-semibold text-text-primary mb-4">
                Investment Value Over Time
              </h3>
              <div
                className="h-[380px]"
                role="img"
                aria-label="Area chart showing investment value growth year by year"
              >
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart
                    data={chartData}
                    margin={{ top: 10, right: 10, left: 10, bottom: 0 }}
                  >
                    <defs>
                      <linearGradient id="roiValueGradient" x1="0" y1="0" x2="0" y2="1">
                        <stop
                          offset="5%"
                          stopColor={isProfit ? '#22c55e' : '#ef4444'}
                          stopOpacity={0.6}
                        />
                        <stop
                          offset="95%"
                          stopColor={isProfit ? '#22c55e' : '#ef4444'}
                          stopOpacity={0.05}
                        />
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" stroke="rgb(51 65 85)" opacity={0.5} />
                    <XAxis
                      dataKey="year"
                      tick={{ fill: 'rgb(148 163 184)', fontSize: 12 }}
                      tickLine={{ stroke: 'rgb(71 85 105)' }}
                      axisLine={{ stroke: 'rgb(71 85 105)' }}
                      interval={Math.max(0, Math.floor(years / 10) - 1)}
                    />
                    <YAxis
                      tick={{ fill: 'rgb(148 163 184)', fontSize: 12 }}
                      tickLine={{ stroke: 'rgb(71 85 105)' }}
                      axisLine={{ stroke: 'rgb(71 85 105)' }}
                      tickFormatter={(value) => {
                        const v = Number(value);
                        return v >= 1000000
                          ? `$${(v / 1000000).toFixed(1)}M`
                          : v >= 1000
                            ? `$${(v / 1000).toFixed(0)}K`
                            : `$${v}`;
                      }}
                    />
                    <Tooltip
                      contentStyle={tooltipStyle}
                      formatter={(value) => [formatCurrency(Number(value)), 'Value']}
                      labelStyle={{ color: 'rgb(148 163 184)', marginBottom: 4 }}
                    />
                    <ReferenceLine
                      y={initialInvestment}
                      stroke="rgb(100 116 139)"
                      strokeDasharray="4 4"
                      label={{
                        value: 'Initial',
                        fill: 'rgb(100 116 139)',
                        fontSize: 11,
                        position: 'insideTopRight',
                      }}
                    />
                    <Area
                      type="monotone"
                      dataKey="Value"
                      stroke={isProfit ? '#22c55e' : '#ef4444'}
                      strokeWidth={2}
                      fill="url(#roiValueGradient)"
                    />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Bar Chart - Profit / Loss Breakdown */}
            <div className="bg-dark-surface border border-dark-border rounded-xl p-6">
              <h3 className="text-lg font-semibold text-text-primary mb-4">
                Return Breakdown
              </h3>
              <div
                className="h-[280px]"
                role="img"
                aria-label="Bar chart comparing initial investment and net profit or loss"
              >
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart
                    data={barData}
                    margin={{ top: 10, right: 10, left: 10, bottom: 0 }}
                    layout="vertical"
                  >
                    <CartesianGrid
                      strokeDasharray="3 3"
                      stroke="rgb(51 65 85)"
                      opacity={0.5}
                      horizontal={false}
                    />
                    <XAxis
                      type="number"
                      tick={{ fill: 'rgb(148 163 184)', fontSize: 12 }}
                      tickLine={{ stroke: 'rgb(71 85 105)' }}
                      axisLine={{ stroke: 'rgb(71 85 105)' }}
                      tickFormatter={(value) => {
                        const v = Number(value);
                        return v >= 1000000
                          ? `$${(v / 1000000).toFixed(1)}M`
                          : v >= 1000
                            ? `$${(v / 1000).toFixed(0)}K`
                            : `$${v}`;
                      }}
                    />
                    <YAxis
                      type="category"
                      dataKey="name"
                      tick={{ fill: 'rgb(148 163 184)', fontSize: 12 }}
                      tickLine={false}
                      axisLine={false}
                      width={80}
                    />
                    <Tooltip
                      contentStyle={tooltipStyle}
                      formatter={(value) => formatCurrency(Number(value))}
                      labelStyle={{ color: 'rgb(148 163 184)', marginBottom: 4 }}
                    />
                    <Bar dataKey="Initial" fill="#3b82f6" radius={[0, 4, 4, 0]} stackId="a" />
                    <Bar
                      dataKey="Net Profit"
                      fill="#22c55e"
                      radius={[0, 4, 4, 0]}
                      stackId="a"
                    />
                    <Bar dataKey="Loss" fill="#ef4444" radius={[0, 4, 4, 0]} stackId="a" />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>
        )}

        {/* In-Article Ad */}
        <div className="mt-8">
          <AdSense slot="in-article" variant="in-feed" />
        </div>

        {/* SEO Content Section */}
        <div className="mt-12 space-y-8">
          <div className="bg-dark-surface border border-dark-border rounded-xl p-6 sm:p-8">
            <h2 className="text-2xl font-bold text-text-primary mb-4">
              What is ROI and Why Does It Matter?
            </h2>
            <div className="prose prose-invert max-w-none text-text-secondary space-y-4">
              <p>
                Return on Investment (ROI) is a performance metric used to evaluate the
                efficiency or profitability of an investment. It compares the gain or loss
                relative to the cost of that investment. The formula is straightforward:
              </p>
              <div className="bg-dark-elevated border border-dark-border rounded-lg p-4 my-4">
                <p className="text-text-primary font-mono text-center text-lg">
                  ROI = (Net Profit / Initial Investment) × 100
                </p>
              </div>
              <p>
                Where <strong className="text-text-primary">Net Profit</strong> = Final Value
                − Initial Investment − Additional Costs.
              </p>
              <h3 className="text-xl font-semibold text-text-primary mt-6 mb-2">
                Total Return vs. Annualized Return (CAGR)
              </h3>
              <p>
                Total return tells you how much you made or lost over the entire holding period.
                But when comparing two investments held for different durations, annualized
                return (CAGR) is more useful. CAGR smooths out the compounding effect and
                expresses performance as an equivalent yearly rate.
              </p>
              <div className="bg-dark-elevated border border-dark-border rounded-lg p-4 my-4">
                <p className="text-text-primary font-mono text-center text-lg">
                  CAGR = (Final Value / Initial Investment)<sup>1/Years</sup> − 1
                </p>
              </div>
              <p>
                For example, if you invested $10,000 and it grew to $15,000 over 5 years, your
                total return is 50% but your CAGR is approximately 8.45% per year. This means
                the investment compounded at 8.45% annually to produce the same result.
              </p>
              <h3 className="text-xl font-semibold text-text-primary mt-6 mb-2">
                Limitations of ROI
              </h3>
              <p>
                ROI does not account for the time value of money beyond what CAGR captures. It
                also ignores risk — two investments with identical ROI may have very different
                volatility profiles. For a more complete picture, consider risk-adjusted metrics
                like Sharpe ratio, or use ROI alongside other tools such as IRR (Internal Rate
                of Return) and NPV (Net Present Value).
              </p>
            </div>
          </div>

          {/* FAQ Section */}
          <div className="bg-dark-surface border border-dark-border rounded-xl p-6 sm:p-8">
            <h2 className="text-2xl font-bold text-text-primary mb-6">
              Frequently Asked Questions
            </h2>
            <div className="space-y-6">
              {FAQ_ITEMS.map((item, index) => (
                <div key={index}>
                  <h3 className="text-lg font-semibold text-text-primary mb-2">
                    {item.question}
                  </h3>
                  <p className="text-text-secondary leading-relaxed">{item.answer}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer Ad */}
        <div className="mt-8">
          <AdSense slot="footer" variant="banner" />
        </div>
      </div>
    </>
  );
}
